package com.rj.engine;

import com.rj.model.TradeSignal;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardOpenOption;
import java.time.format.DateTimeFormatter;

/**
 * Async CSV logger for all alpha-signals generated by strategies.
 */
public class SignalJournal {
    private static final Logger log = LoggerFactory.getLogger(SignalJournal.class);
    private static final String CSV_HEADER = "timestamp,symbol,strategy,direction,confidence,entry,sl,tp,atr,reason\n";
    private final Path logPath;

    public SignalJournal() {
        this.logPath = Path.of("data/journal/signals.csv");
        initialize();
    }

    private void initialize() {
        try {
            Files.createDirectories(logPath.getParent());
            if (!Files.exists(logPath)) {
                Files.writeString(logPath, CSV_HEADER);
            }
        } catch (IOException e) {
            log.error("Failed to initialize SignalJournal", e);
        }
    }

    public void logSignal(TradeSignal signal) {
        String line = String.format("%s,%s,%s,%s,%s,%.2f,%.2f,%.2f,%.2f,\"%s\"\n",
                DateTimeFormatter.ISO_INSTANT.format(signal.getGeneratedAt()),
                signal.getSymbol(),
                signal.getStrategyId(),
                signal.getDirection(),
                signal.getConfidenceLevel(),
                signal.getSuggestedEntry(),
                signal.getSuggestedStopLoss(),
                signal.getSuggestedTarget(),
                signal.getAtr(),
                signal.getReason().replace("\"", "'")
        );

        // Run in virtual thread to avoid blocking the strategy engine
        Thread.startVirtualThread(() -> {
            try {
                Files.writeString(logPath, line, StandardOpenOption.APPEND);
            } catch (IOException e) {
                log.error("Failed to write to SignalJournal", e);
            }
        });
    }
}
