package com.rj.engine;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.SerializationFeature;
import com.fasterxml.jackson.datatype.jsr310.JavaTimeModule;
import com.rj.model.ExecutionMode;
import com.rj.model.OpenPosition;
import com.rj.model.TradeRecord;
import com.rj.model.TradeSignal;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.BufferedWriter;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardOpenOption;
import java.time.Instant;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.*;
import java.util.concurrent.CopyOnWriteArrayList;

/**
 * Append-only NDJSON transaction journal.
 *
 * <p>Every significant event is written as a JSON object on its own line to
 * {@code data/journal/journal-YYYY-MM-DD-<MODE>.ndjson}.</p>
 *
 * <p>Events logged:</p>
 * <ul>
 *   <li>{@code SIGNAL_GENERATED} — compound signal ready for risk</li>
 *   <li>{@code SIGNAL_REJECTED}  — signal blocked by risk / cooldown / time</li>
 *   <li>{@code ORDER_ENTRY}      — entry fill (or rejection)</li>
 *   <li>{@code ORDER_EXIT}       — exit fill with reason</li>
 *   <li>{@code TRADE_CLOSED}     — full trade record with PnL and metrics</li>
 * </ul>
 *
 * <p>Thread-safe: all writes are synchronized on the writer lock.
 * Also maintains an in-memory list of closed {@link TradeRecord}s for
 * same-session analysis without re-parsing the file.</p>
 */
public class TradeJournal {

    private static final Logger log = LoggerFactory.getLogger(TradeJournal.class);
    private static final ZoneId IST = ZoneId.of("Asia/Kolkata");

    private final ExecutionMode mode;
    private final Path journalFile;
    private final ObjectMapper mapper;
    private final Object writeLock = new Object();

    /** In-memory list of closed trades for real-time analysis queries. */
    private final CopyOnWriteArrayList<TradeRecord> closedTrades = new CopyOnWriteArrayList<>();

    public TradeJournal(ExecutionMode mode) {
        this(mode, Path.of("data", "journal"));
    }

    public TradeJournal(ExecutionMode mode, Path journalDir) {
        this.mode = mode;
        this.mapper = new ObjectMapper()
                .registerModule(new JavaTimeModule())
                .disable(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS);

        try {
            Files.createDirectories(journalDir);
            String fileName = "journal-" + LocalDate.now(IST) + "-" + mode.name().toLowerCase() + ".ndjson";
            this.journalFile = journalDir.resolve(fileName);
            log.info("TradeJournal opened: {}", journalFile.toAbsolutePath());
        } catch (IOException e) {
            throw new RuntimeException("Cannot create journal directory: " + journalDir, e);
        }
    }

    // ── Public logging API ────────────────────────────────────────────────────

    /** Log a compound signal generated by StrategyEvaluator. */
    public void logSignalGenerated(TradeSignal signal) {
        Map<String, Object> event = event("SIGNAL_GENERATED");
        event.put("correlationId", signal.getCorrelationId());
        event.put("symbol", signal.getSymbol());
        event.put("direction", signal.getDirection());
        event.put("confidence", signal.getConfidence());
        event.put("entry", signal.getSuggestedEntry());
        event.put("stopLoss", signal.getSuggestedStopLoss());
        event.put("target", signal.getSuggestedTarget());
        event.put("strategyId", signal.getStrategyId());
        event.put("rMultiple", signal.rMultiple());
        event.put("votes", signal.getTimeframeVotes().toString());
        write(event);
    }

    /** Log a signal that was rejected (by risk, cooldown, time, etc.). */
    public void logSignalRejected(TradeSignal signal, String reason) {
        Map<String, Object> event = event("SIGNAL_REJECTED");
        event.put("correlationId", signal.getCorrelationId());
        event.put("symbol", signal.getSymbol());
        event.put("direction", signal.getDirection());
        event.put("reason", reason);
        write(event);
    }

    /** Log an entry order fill (or rejection). */
    public void logOrderEntry(TradeSignal signal, com.rj.model.OrderFill fill) {
        Map<String, Object> event = event("ORDER_ENTRY");
        event.put("correlationId", signal.getCorrelationId());
        event.put("symbol", signal.getSymbol());
        event.put("direction", signal.getDirection());
        event.put("mode", mode);
        event.put("success", fill.isSuccess());
        event.put("fillPrice", fill.getFillPrice());
        event.put("fillQty", fill.getFillQuantity());
        event.put("orderId", fill.getOrderId());
        if (!fill.isSuccess()) event.put("rejectReason", fill.getRejectReason());
        write(event);
    }

    /** Log an exit order fill. */
    public void logOrderExit(OpenPosition pos, com.rj.model.OrderFill fill,
                             PositionMonitor.ExitReason reason) {
        Map<String, Object> event = event("ORDER_EXIT");
        event.put("correlationId", pos.getCorrelationId());
        event.put("symbol", pos.getSymbol());
        event.put("direction", pos.getDirection());
        event.put("exitReason", reason);
        event.put("success", fill.isSuccess());
        event.put("fillPrice", fill.getFillPrice());
        event.put("entryPrice", pos.getEntryPrice());
        double priceDiff = pos.getDirection().toString().equals("BUY")
                ? fill.getFillPrice() - pos.getEntryPrice()
                : pos.getEntryPrice() - fill.getFillPrice();
        event.put("grossPnl", priceDiff * pos.getQuantity());
        write(event);
    }

    /** Log a fully closed trade (called after exit fill confirmed). */
    public void logTradeClosed(TradeRecord trade) {
        closedTrades.add(trade);

        Map<String, Object> event = event("TRADE_CLOSED");
        event.put("correlationId", trade.getCorrelationId());
        event.put("symbol", trade.getSymbol());
        event.put("strategyId", trade.getStrategyId());
        event.put("mode", trade.getMode());
        event.put("direction", trade.getDirection());
        event.put("entryPrice", trade.getEntryPrice());
        event.put("exitPrice", trade.getExitPrice());
        event.put("quantity", trade.getQuantity());
        event.put("pnl", trade.getPnl());
        event.put("pnlPct", trade.getPnlPct());
        event.put("rMultiple", trade.getRMultipleAchieved());
        event.put("exitReason", trade.getExitReason());
        event.put("entryTime", trade.getEntryTime());
        event.put("exitTime", trade.getExitTime());
        event.put("holdSeconds", trade.getHoldDuration() != null
                ? trade.getHoldDuration().toSeconds() : null);
        event.put("maxAdverseExcursion", trade.getMaxAdverseExcursion());
        event.put("maxFavorableExcursion", trade.getMaxFavorableExcursion());
        event.put("confidence", trade.getEntryConfidence());
        event.put("winner", trade.isWinner());
        write(event);
    }

    /** Generic event log (for custom entries from any layer). */
    public void log(String eventType, Map<String, Object> fields) {
        Map<String, Object> event = event(eventType);
        event.putAll(fields);
        write(event);
    }

    // ── In-memory query ───────────────────────────────────────────────────────

    /** Returns an unmodifiable snapshot of all closed trades this session. */
    public List<TradeRecord> closedTrades() {
        return Collections.unmodifiableList(new ArrayList<>(closedTrades));
    }

    public int closedTradeCount() {
        return closedTrades.size();
    }

    // ── Private helpers ───────────────────────────────────────────────────────

    private Map<String, Object> event(String type) {
        Map<String, Object> m = new LinkedHashMap<>();
        m.put("ts", Instant.now().toString());
        m.put("type", type);
        m.put("mode", mode.name());
        return m;
    }

    private void write(Map<String, Object> event) {
        try {
            String line = mapper.writeValueAsString(event);
            synchronized (writeLock) {
                try (BufferedWriter w = Files.newBufferedWriter(
                        journalFile, StandardOpenOption.CREATE, StandardOpenOption.APPEND)) {
                    w.write(line);
                    w.newLine();
                }
            }
        } catch (IOException e) {
            log.error("TradeJournal write failed: {}", e.getMessage(), e);
        } catch (Exception e) {
            log.error("TradeJournal serialization failed: {}", e.getMessage(), e);
        }
    }
}
